import { code, choice, written, check, value, valueField } from './helpers.js';
export default {
  id: 'foundations',
  weeks: 'Weeks 2–3',
  number: '02',
  title: 'Syntax & objects',
  subtitle: 'Operators, data structures, and their behaviour',
  source: 'Lecture 2 · PS 3 · Lab 3',
  sources: ['Week 2/Lec-2.html', 'Week 3/PS-03.html', 'Week 3/Lab-03.html'],
  learn: [
    code(
      'syntax',
      'Read and repair code',
      'Close the missing quotation mark so the script runs. Store x + 5 in z.',
      'x <- 10\ny <- "apple\nz <- x + 5\nprint(z)',
      'x <- 10\ny <- "apple"\nz <- x + 5\nprint(z)',
      'An unclosed string makes the parser wait for its ending. In a script, later lines may become part of that unfinished string.',
      [value('y', '"apple"'), value('z', '15')],
      {
        concept:
          'R is case-sensitive: x and X are different names. Use one command per line; # begins a comment.',
        hints: ['The error is on the line that creates y.', 'y <- "apple"'],
      },
    ),
    code(
      'division',
      'Whole groups and leftovers',
      'A shop packs 17 items in boxes holding 5 each. Store full boxes in boxes and unpacked items in leftover.',
      'items <- 17\ncapacity <- 5',
      'items <- 17\ncapacity <- 5\nboxes <- items %/% capacity\nleftover <- items %% capacity\nboxes\nleftover',
      '%/% gives the number of complete groups: 3. %% gives the remainder: 2. For these positive integers, 17 = 3 * 5 + 2.',
      [value('boxes', '3'), value('leftover', '2')],
      {
        concept: '%/% is integer division. %% is the remainder operator.',
        hints: [
          'Use %/% and %% on the same pair of values.',
          'boxes <- items %/% capacity\nleftover <- items %% capacity',
        ],
      },
    ),
    code(
      'comparisons',
      'Ask a yes-or-no question',
      'Create stock = 17 and order = 5. Store stock > order in enough and stock == order in exact.',
      'stock <- 17\norder <- 5',
      'stock <- 17\norder <- 5\nenough <- stock > order\nexact <- stock == order',
      'Comparisons return logical values: TRUE or FALSE. == tests equality; <- assigns a value.',
      [value('enough', 'TRUE'), value('exact', 'FALSE')],
      {
        concept: 'Use >, >=, <, <=, == and != to compare values.',
        hints: ['Use ==, not =, to test equality.', 'exact <- stock == order'],
      },
    ),
    code(
      'logic',
      'Combine conditions',
      'With in_stock = TRUE and paid = FALSE, store in_stock & paid in ready, in_stock | paid in either, and !paid in unpaid.',
      'in_stock <- TRUE\npaid <- FALSE',
      'in_stock <- TRUE\npaid <- FALSE\nready <- in_stock & paid\neither <- in_stock | paid\nunpaid <- !paid',
      '& requires both conditions. | requires at least one. ! reverses a logical value. Here the results are FALSE, TRUE, TRUE.',
      [value('ready', 'FALSE'), value('either', 'TRUE'), value('unpaid', 'TRUE')],
      {
        hints: ['& means AND, | means OR, ! means NOT.', 'unpaid <- !paid'],
        details:
          '& and | work element by element on vectors. && and || are scalar, short-circuit forms used for single conditions; they are a later topic.',
      },
    ),
    code(
      'vectors',
      'Keep several values together',
      'Create sales with 120, 95, 140, in that order. Store its length in months and its total in total.',
      '# Create and inspect sales.',
      'sales <- c(120, 95, 140)\nmonths <- length(sales)\ntotal <- sum(sales)\nsales',
      'c() combines values into a vector. Atomic vectors hold a single underlying type. Open sales in Objects to inspect each position.',
      [value('sales', 'c(120, 95, 140)'), value('months', '3'), value('total', '355')],
      {
        concept: 'A vector is an ordered collection. length() counts elements; sum() adds them.',
        hints: ['Use c() to combine the three numbers.', 'sales <- c(120, 95, 140)'],
      },
    ),
    code(
      'index',
      'Choose a position',
      'Create sales as c(120, 95, 140). Store the second month in second and months 1 and 3 in selected.',
      'sales <- c(120, 95, 140)',
      'sales <- c(120, 95, 140)\nsecond <- sales[2]\nselected <- sales[c(1, 3)]',
      'R positions start at 1. Square brackets select elements. A vector of positions selects more than one.',
      [value('sales', 'c(120,95,140)'), value('second', '95'), value('selected', 'c(120, 140)')],
      { hints: ['Use sales[2] for the second value.', 'selected <- sales[c(1, 3)]'] },
    ),
    code(
      'sequences',
      'Sequences and vector arithmetic',
      'Create numbers 1 to 10 in numbers, then create squares by squaring the whole vector.',
      '# No loop is needed.',
      'numbers <- 1:10\nsquares <- numbers^2\nsquares',
      'The colon makes a sequence. Arithmetic on a vector applies to each element, so numbers^2 produces ten squares.',
      [value('numbers', '1:10'), value('squares', '(1:10)^2')],
      { hints: ['Use 1:10 to make the sequence.', 'squares <- numbers^2'] },
    ),
    code(
      'character-vectors',
      'Text and logical vectors',
      'Create sizes as c("S", "M", "L", "M"). Store the comparison sizes == "M" in medium.',
      'sizes <- c("S", "M", "L", "M")',
      'sizes <- c("S", "M", "L", "M")\nmedium <- sizes == "M"\nmedium',
      'The comparison runs once per element and returns FALSE, TRUE, FALSE, TRUE. Text values need quotation marks.',
      [value('sizes', 'c("S","M","L","M")'), value('medium', 'c(FALSE, TRUE, FALSE, TRUE)')],
      { hints: ['Compare the entire sizes vector to "M".', 'medium <- sizes == "M"'] },
    ),
    choice(
      'coercion',
      'Mixing types',
      'What values does this vector contain?',
      'mixed <- c(1, "A", TRUE)',
      [
        '1, "A", TRUE with three separate types',
        '"1", "A", "TRUE", all character',
        'An error; mixed types cannot be combined',
      ],
      1,
      'An atomic vector has one type. Combining character, numeric, and logical values converts all of them to character.',
    ),
    code(
      'length',
      'Extend and shorten',
      'Start with x = c(4, 8, 12). Extend its length to 6 and store a copy in extended. Then shorten x to length 2.',
      'x <- c(4, 8, 12)',
      'x <- c(4, 8, 12)\nlength(x) <- 6\nextended <- x\nlength(x) <- 2\nx',
      'Extending a numeric vector adds NA (missing values). Shortening it drops elements. The extended copy preserves the earlier six-element state.',
      [value('extended', 'c(4, 8, 12, NA, NA, NA)'), value('x', 'c(4, 8)')],
      { hints: ['length(x) <- 6 changes the length.', 'Save extended <- x before shortening x.'] },
    ),
    code(
      'beyond-length',
      'Assign beyond the end',
      'Create an empty numeric vector e. Set its third element to 17.',
      'e <- numeric()',
      'e <- numeric()\ne[3] <- 17\ne',
      'Positions 1 and 2 are filled with NA. NA means a value is missing; it is not zero.',
      [value('e', 'c(NA, NA, 17)')],
      { hints: ['Use an index on the left side of <-.', 'e[3] <- 17'] },
    ),
    code(
      'matrix',
      'Arrange values in a matrix',
      'Create m from 1:6 with 2 rows and 3 columns, filled by row.',
      'm <- matrix(1:6, nrow = 2, byrow = TRUE)',
      'm <- matrix(1:6, nrow = 2, byrow = TRUE)\nm\ndim(m)',
      'The first row is 1, 2, 3; the second is 4, 5, 6. Without byrow = TRUE, matrix() fills columns first. All entries have the same underlying type.',
      [value('m', 'matrix(1:6, nrow=2, byrow=TRUE)')],
      {
        concept: 'Matrices have rows and columns. dim() returns their dimensions.',
        hints: ['Pass the vector 1:6 to matrix().', 'Set nrow = 2 and byrow = TRUE.'],
      },
    ),
    code(
      'matrix-names',
      'Name rows and columns',
      'Create the shown matrix, name rows A and B and columns M1, M2, M3. Extract product B’s second month into second_B.',
      'sales <- matrix(c(120, 95, 140, 85, 110, 130), nrow = 2, byrow = TRUE)',
      'sales <- matrix(c(120, 95, 140, 85, 110, 130), nrow = 2, byrow = TRUE)\nrownames(sales) <- c("A", "B")\ncolnames(sales) <- c("M1", "M2", "M3")\nsecond_B <- sales["B", "M2"]\nsales',
      'A matrix uses [row, column]. Names can replace numeric positions. Click a displayed cell in Objects to see its position.',
      [
        value('sales', 'matrix(c(120,95,140,85,110,130), nrow=2, byrow=TRUE)'),
        check(
          'exists("sales", inherits=FALSE) && identical(rownames(sales), c("A", "B"))',
          'Assign row names A and B.',
        ),
        check(
          'exists("sales", inherits=FALSE) && identical(colnames(sales), c("M1", "M2", "M3"))',
          'Assign column names M1, M2, M3.',
        ),
        value('second_B', '110'),
      ],
      { hints: ['Use rownames() and colnames() on the left of <-.', 'second_B <- sales[2, 2]'] },
    ),
    code(
      'summaries',
      'Summarise rows and columns',
      'For the sales matrix, store each product’s total in product_totals and each month’s total in month_totals. Find the busiest month position in best_month.',
      'sales <- matrix(c(120, 95, 140, 85, 110, 130), nrow = 2, byrow = TRUE)',
      'sales <- matrix(c(120, 95, 140, 85, 110, 130), nrow = 2, byrow = TRUE)\nproduct_totals <- rowSums(sales)\nmonth_totals <- colSums(sales)\nbest_month <- which.max(month_totals)',
      'Rows represent products, so rowSums() totals products. Columns represent months, so colSums() totals months. which.max() returns the position of the first maximum.',
      [
        value('product_totals', 'c(355, 325)'),
        value('month_totals', 'c(205, 205, 270)'),
        value('best_month', '3'),
      ],
      {
        bridge: true,
        concept:
          'Preparation for Lab 3: rowSums(), colSums(), rowMeans(), colMeans(), and which.max().',
        hints: [
          'Use one row summary and one column summary.',
          'best_month <- which.max(month_totals)',
        ],
      },
    ),
    code(
      'lists',
      'Different objects in one list',
      'Create a list called report with revenue = 120, label = "October", and sales = c(40, 30, 50). Extract the sales vector into units.',
      '# Create the named list.',
      'report <- list(revenue = 120, label = "October", sales = c(40, 30, 50))\nunits <- report$sales\nreport',
      'A list holds objects of different types. report["sales"] returns a one-element list; report[["sales"]] and report$sales extract the contained vector.',
      [
        check(
          'exists("report", inherits=FALSE) && is.list(report) && setequal(names(report), c("revenue", "label", "sales"))',
          'Create a named list with revenue, label, and sales.',
        ),
        valueField('report', 'revenue', '120'),
        valueField('report', 'label', '"October"'),
        valueField('report', 'sales', 'c(40,30,50)'),
        value('units', 'c(40, 30, 50)'),
      ],
      { hints: ['Use list(name = value, ...).', 'units <- report$sales'] },
    ),
    code(
      'dataframes',
      'A table with different column types',
      'Create students with columns ID = 1:3, Name = c("Ada", "Ben", "Cem"), Score = c(78, 91, 88). Store the Score column mean in average.',
      '# Build a data frame.',
      'students <- data.frame(ID = 1:3, Name = c("Ada", "Ben", "Cem"), Score = c(78, 91, 88))\naverage <- mean(students$Score)\nstr(students)',
      'Each data-frame column can have its own type, but columns must have compatible lengths. Here numeric IDs and scores sit beside character names.',
      [
        check(
          'exists("students", inherits=FALSE) && is.data.frame(students) && setequal(names(students), c("ID", "Name", "Score"))',
          'Create a data frame with ID, Name, and Score columns.',
        ),
        valueField('students', 'ID', '1:3'),
        valueField('students', 'Name', 'c("Ada","Ben","Cem")'),
        valueField('students', 'Score', 'c(78,91,88)'),
        value('average', 'mean(c(78, 91, 88))'),
      ],
      {
        hints: ['Use data.frame() and named columns.', 'average <- mean(students$Score)'],
        details:
          'as.data.frame(m) converts a matrix into a data frame. str() inspects its structure. Use students[2, "Score"] to select one cell.',
      },
    ),
    code(
      'factors',
      'Categories and levels',
      'Create department as a factor from c("IT", "HR", "IT", "Sales"). Store its levels in categories and category counts in counts.',
      'labels <- c("IT", "HR", "IT", "Sales")',
      'labels <- c("IT", "HR", "IT", "Sales")\ndepartment <- factor(labels)\ncategories <- levels(department)\ncounts <- table(department)\ndepartment\ncounts',
      'A factor represents categories with stored levels. The default levels here are HR, IT, Sales. IT occurs twice; the others occur once.',
      [
        check(
          'exists("department", inherits=FALSE) && is.factor(department) && identical(as.character(department),c("IT","HR","IT","Sales"))',
          'department must be a factor containing IT, HR, IT, Sales, in that order. Use factor(labels).',
        ),
        check(
          'exists("categories",inherits=FALSE) && exists("department",inherits=FALSE) && identical(categories,levels(department)) && setequal(categories,c("HR","IT","Sales"))',
          'Set categories <- levels(department). The three categories are HR, IT, and Sales; their order can follow your factor levels.',
        ),
        valueField(
          'counts',
          'HR',
          '1',
          'Use counts <- table(department) to create labelled category counts.',
        ),
        valueField('counts', 'IT', '2', 'Use counts <- table(department); IT appears twice.'),
        valueField('counts', 'Sales', '1', 'Use counts <- table(department); Sales appears once.'),
      ],
      {
        hints: [
          'factor() creates categories; levels() retrieves them.',
          'counts <- table(department)',
        ],
        details:
          'Assigning a new label not in levels() produces NA and a warning. Add it to the levels first, or recreate the factor with the intended levels.',
      },
    ),
    code(
      'ordered-factor',
      'Give categories an order',
      'Create education as an ordered factor with High School, Bachelor, Master, PhD, in that order.',
      'labels <- c("Master", "Bachelor", "PhD", "High School")',
      'labels <- c("Master", "Bachelor", "PhD", "High School")\neducation <- factor(labels, levels = c("High School", "Bachelor", "Master", "PhD"), ordered = TRUE)\neducation',
      'The order of levels is explicit and separate from the order of observations.',
      [
        check(
          'exists("education", inherits=FALSE) && is.ordered(education) && identical(levels(education), c("High School", "Bachelor", "Master", "PhD")) && identical(as.character(education),c("Master","Bachelor","PhD","High School"))',
          'Set the levels explicitly and use ordered = TRUE.',
        ),
      ],
      { hints: ['Pass levels = c(...) to factor().', 'Add ordered = TRUE.'] },
    ),
    code(
      'conversion',
      'Convert a type',
      'Create z = 0:9, convert it to character in digits, then back to integers in restored.',
      'z <- 0:9',
      'z <- 0:9\ndigits <- as.character(z)\nrestored <- as.integer(digits)\nclass(z)\nclass(digits)\nclass(restored)',
      'as.character() converts numbers to text. as.integer() converts numeric text back to integers. Non-numeric text such as "apple" converts to NA with a warning.',
      [
        value('z', '0:9'),
        value('digits', 'as.character(0:9)'),
        check(
          'exists("restored", inherits=FALSE) && identical(restored, 0:9)',
          'Convert digits back with as.integer().',
        ),
      ],
      {
        hints: [
          'Use the as.character() and as.integer() functions.',
          'restored <- as.integer(digits)',
        ],
      },
    ),
    code(
      'attributes',
      'Values with metadata',
      'Create x as a matrix of 1:9 with 3 rows. Store its dimensions in shape. Add a source attribute equal to "Practice".',
      'x <- matrix(1:9, nrow = 3)',
      'x <- matrix(1:9, nrow = 3)\nshape <- attr(x, "dim")\nattr(x, "source") <- "Practice"\nattributes(x)',
      'Attributes describe an object: dimensions, names, levels, and other metadata. Changing metadata is different from changing the values.',
      [
        value('x', 'matrix(1:9,nrow=3)'),
        value('shape', 'c(3L,3L)'),
        check(
          'exists("x", inherits=FALSE) && identical(attr(x,"source"), "Practice")',
          'Set attr(x, "source") to "Practice".',
        ),
      ],
      {
        hints: ['attr(x, "dim") reads one attribute.', 'attr(x, "source") <- "Practice"'],
        details:
          'A vector can become a matrix with dim(x) <- c(rows, columns), provided the dimensions fit its length. Remove an attribute with attr(x, "source") <- NULL.',
      },
    ),
    code(
      'unclass',
      'Class and underlying structure',
      'Create the data frame below, then store unclass(df) in raw. Store class(raw) in raw_class and class(df) in original_class.',
      'df <- data.frame(A = 1:3, B = 4:6)',
      'df <- data.frame(A = 1:3, B = 4:6)\nraw <- unclass(df)\nraw_class <- class(raw)\noriginal_class <- class(df)',
      'unclass(df) returns its underlying list without the explicit data.frame class. class(raw) is "list", not NULL. df itself is unchanged.',
      [
        check(
          'exists("df",inherits=FALSE) && is.data.frame(df)',
          'Create df with data.frame(A=1:3, B=4:6).',
        ),
        valueField('df', 'A', '1:3'),
        valueField('df', 'B', '4:6'),
        check(
          'exists("raw",inherits=FALSE) && exists("df",inherits=FALSE) && is.list(raw) && !is.data.frame(raw) && setequal(names(raw),names(df)) && all(vapply(names(df), function(nm) isTRUE(all.equal(raw[[nm]],df[[nm]], check.attributes=FALSE, tolerance=0)), logical(1)))',
          'Save the underlying list in raw with raw <- unclass(df).',
        ),
        valueField('raw', 'A', '1:3'),
        valueField('raw', 'B', '4:6'),
        value('raw_class', '"list"'),
        value('original_class', '"data.frame"'),
      ],
      {
        hints: [
          'Save the returned object; unclass() does not change df in place.',
          'raw_class <- class(raw)',
        ],
        details:
          'mode() describes a broad underlying storage category; class() describes how an object behaves. A matrix of numbers has mode "numeric" and class c("matrix", "array"). Change structure with matrix() or factor(), rather than arbitrarily relabelling class().',
      },
    ),
    code(
      'labels',
      'The clothing-label challenge',
      'Cut repeats Normal, Normal, Slim, Slim. Size repeats S, M, L. Find the labels on card 175; store them in cut and size.',
      'card <- 175\ncuts <- c("Normal", "Normal", "Slim", "Slim")\nsizes <- c("S", "M", "L")',
      'card <- 175\ncuts <- c("Normal", "Normal", "Slim", "Slim")\nsizes <- c("S", "M", "L")\ncut <- cuts[(card - 1) %% length(cuts) + 1]\nsize <- sizes[(card - 1) %% length(sizes) + 1]\ncut\nsize',
      'Subtract 1 to create a zero-based cycle, take the remainder, then add 1 for an R index. Card 175 has Slim cut and size S.',
      [value('cut', '"Slim"'), value('size', '"S"')],
      {
        source: 'Lecture 2 · Opening challenge (adapted labels)',
        hints: [
          'For a pattern of length k, use (card - 1) %% k + 1.',
          'cut <- cuts[(card - 1) %% 4 + 1]',
        ],
      },
    ),
    code(
      'repeat-update',
      'Repeat a state update',
      'Start balance at 100. Increase it by 10% three times using a for loop. Store each year-end value in history.',
      'balance <- 100\nhistory <- numeric(3)\nfor (year in 1:3) {\n  # Update balance and store history[year].\n}',
      'balance <- 100\nhistory <- numeric(3)\nfor (year in 1:3) {\n  balance <- balance * 1.10\n  history[year] <- balance\n}\nbalance\nhistory',
      'The loop runs once for each value of year. The new balance becomes the next iteration’s starting value: 110, 121, 133.1.',
      [value('balance', '133.1'), value('history', 'c(110, 121, 133.1)')],
      {
        bridge: true,
        manual:
          'The final balance and history are checked. Also review that your for loop repeats the update three times.',
        concept:
          'Preparation for Lab 3: a for loop repeats the commands inside braces. Full control-flow lessons will follow later.',
        hints: [
          'Update balance inside the braces.',
          'balance <- balance * 1.10\nhistory[year] <- balance',
        ],
      },
    ),
  ],
  practice: [
    code(
      'ps3-debug',
      'PS 3 · Syntax debugging',
      'Identify and repair the parsing problem. Keep x = 10 and compute z = x + 5.',
      'x <- 10\ny <- "apple\nz <- x + 5\nprint(z)',
      'x <- 10\ny <- "apple"\nz <- x + 5\nprint(z)',
      'The quotation mark ending "apple" is missing. R cannot parse the intended separate statements until the string is closed.',
      [value('y', '"apple"'), value('z', '15')],
      { source: 'PS 3 · Q1' },
    ),
    code(
      'ps3-operators',
      'PS 3 · Operator practice',
      'Store a %% b, a %/% b, and their sum in remainder, quotient, combined. Store a > b, (a > b) & p, (a < b) | q in greater, both, either.',
      'a <- 17\nb <- 5\np <- TRUE\nq <- FALSE',
      'a <- 17\nb <- 5\np <- TRUE\nq <- FALSE\nremainder <- a %% b\nquotient <- a %/% b\ncombined <- remainder + quotient\ngreater <- a > b\nboth <- (a > b) & p\neither <- (a < b) | q',
      'The remainder is 2, the integer quotient 3, and the sum 5. The logical answers are TRUE, TRUE, FALSE.',
      [
        value('remainder', '2'),
        value('quotient', '3'),
        value('combined', '5'),
        value('greater', 'TRUE'),
        value('both', 'TRUE'),
        value('either', 'FALSE'),
      ],
      { source: 'PS 3 · Q2' },
    ),
    code(
      'ps3-length',
      'PS 3 · Changing object length',
      'Start x as c(4, 8, 12), extend it to length 6, store that intermediate state in extended, then truncate x to length 2.',
      'x <- c(4, 8, 12)',
      'x <- c(4, 8, 12)\nlength(x) <- 6\nextended <- x\nlength(x) <- 2\nx',
      'The extension adds three NA values. The final x contains 4 and 8.',
      [value('extended', 'c(4, 8, 12, NA, NA, NA)'), value('x', 'c(4,8)')],
      { source: 'PS 3 · Part B' },
    ),
    code(
      'ps3-matrix',
      'PS 3 · Matrices and indexing',
      'Create m = matrix(1:12, nrow = 3, byrow = TRUE). Name rows R1–R3, columns C1–C4. Store [2,3] in selected, row sums in row_totals, column sums in column_totals.',
      '# Create, name, extract, and summarise.',
      'm <- matrix(1:12, nrow = 3, byrow = TRUE)\nrownames(m) <- c("R1", "R2", "R3")\ncolnames(m) <- c("C1", "C2", "C3", "C4")\nselected <- m[2, 3]\nrow_totals <- rowSums(m)\ncolumn_totals <- colSums(m)',
      'The selected value is 7. Row totals are 10, 26, 42; column totals are 15, 18, 21, 24.',
      [
        value('m', 'matrix(1:12,nrow=3,byrow=TRUE)'),
        check(
          'exists("m", inherits=FALSE) && identical(rownames(m),c("R1","R2","R3")) && identical(colnames(m),c("C1","C2","C3","C4"))',
          'Assign all row and column names.',
        ),
        value('selected', '7'),
        value('row_totals', 'c(10,26,42)'),
        value('column_totals', 'c(15,18,21,24)'),
      ],
      {
        source: 'PS 3 · Part C',
        hints: [
          'matrix(..., byrow = TRUE) fills rows first.',
          'selected <- m[2, 3]\nrow_totals <- rowSums(m)\ncolumn_totals <- colSums(m)',
        ],
      },
    ),
    code(
      'lab3-population',
      'Lab 3 · Two cities',
      'Each year 1% of A moves to B and 2% of B moves to A. Start at A = 10000, B = 20000. Compute both populations after 5 years in cityA and cityB. Both flows must use that year’s starting populations.',
      'cityA <- 10000\ncityB <- 20000\n# Update the two cities for five years.',
      'cityA <- 10000\ncityB <- 20000\nfor (year in 1:5) {\n  moveA <- 0.01 * cityA\n  moveB <- 0.02 * cityB\n  cityA <- cityA - moveA + moveB\n  cityB <- cityB + moveA - moveB\n}\ncityA\ncityB',
      'Calculate both migration flows before changing either city. After five years, A ≈ 11412.659743 and B ≈ 18587.340257. Their sum remains 30000. Do not round intermediate populations.',
      [
        value(
          'cityA',
          '11412.659743',
          'Calculate both flows from the old populations before updating either city.',
        ),
        value('cityB', '18587.340257'),
        check(
          'exists("cityA",inherits=FALSE) && exists("cityB",inherits=FALSE) && abs(cityA + cityB - 30000) < 1e-6',
          'Total population must remain 30000.',
        ),
      ],
      {
        source: 'Lab 3 · Exercise 1',
        hints: [
          'See Learn → Repeat a state update for a loop introduction.',
          'Inside each year, calculate moveA and moveB first; then update cityA and cityB.',
        ],
      },
    ),
    code(
      'lab3-boxes',
      'Lab 3 · Packaging and leftovers',
      'Pack 983 USB drives in boxes holding 24. Store the number of full boxes in full_boxes and remaining drives in leftover.',
      'total <- 983\nper_box <- 24',
      'total <- 983\nper_box <- 24\nfull_boxes <- total %/% per_box\nleftover <- total %% per_box',
      'There are 40 full boxes and 23 leftover drives. If shipping every drive, you would need an additional partially filled box; the question asks for full boxes.',
      [value('full_boxes', '40'), value('leftover', '23')],
      {
        source: 'Lab 3 · Exercise 2',
        hints: ['Integer division counts full boxes.', 'leftover <- total %% per_box'],
      },
    ),
    code(
      'lab3-grade',
      'Lab 3 · Weighted course grade',
      'In this exercise, weights are Midterm 35%, Final 45%, Project 20%. Scores are 78, 91; project rubric items are 86, 92, 88, 90. Store project mean in project and overall weighted grade in overall.',
      'midterm <- 78\nfinal <- 91\nrubric <- c(86, 92, 88, 90)',
      'midterm <- 78\nfinal <- 91\nrubric <- c(86, 92, 88, 90)\nproject <- mean(rubric)\noverall <- 0.35 * midterm + 0.45 * final + 0.20 * project',
      'Project = 89 and overall = 86.05. These weights belong to the exercise, not the actual MIS 130 grading scheme.',
      [value('project', '89'), value('overall', '86.05')],
      {
        source: 'Lab 3 · Exercise 3',
        hints: [
          'Compute the project mean first.',
          'Multiply each score by its decimal weight, then add.',
        ],
      },
    ),
    code(
      'lab3-sales',
      'Lab 3 · Monthly sales roll-up',
      'A sells 120, 95, 140; B sells 85, 110, 130. Store sales as a 2×3 matrix (products by months). Compute total_units_per_product, grand_total, month_totals, and best_month (position 1–3).',
      '# Store and summarise sales.',
      'sales <- matrix(c(120, 95, 140, 85, 110, 130), nrow = 2, byrow = TRUE)\nrownames(sales) <- c("A", "B")\ncolnames(sales) <- c("M1", "M2", "M3")\ntotal_units_per_product <- rowSums(sales)\ngrand_total <- sum(sales)\nmonth_totals <- colSums(sales)\nbest_month <- unname(which.max(month_totals))',
      'Products total 355 and 325, grand total 680. Months total 205, 205, 270, so month 3 is highest.',
      [
        value('sales', 'matrix(c(120,95,140,85,110,130),nrow=2,byrow=TRUE)'),
        value('total_units_per_product', 'c(355,325)'),
        value('grand_total', '680'),
        value('month_totals', 'c(205,205,270)'),
        value('best_month', '3'),
      ],
      {
        source: 'Lab 3 · Exercise 4',
        hints: [
          'Products are rows; months are columns.',
          'Use rowSums(), sum(), colSums(), then which.max().',
        ],
      },
    ),
    code(
      'lab3-departments',
      'Lab 3 · Department performance',
      'Rows: IT (88,92,79,85), HR (75,81,69,74), Sales (91,95,89,93). Create scores with named rows and Q1–Q4 columns. Compute dept_avg, quarter_avg, best_dept (name), and dept_factor from the department names.',
      '# Create the report.',
      'scores <- matrix(c(88,92,79,85,75,81,69,74,91,95,89,93), nrow=3, byrow=TRUE)\nrownames(scores) <- c("IT", "HR", "Sales")\ncolnames(scores) <- c("Q1", "Q2", "Q3", "Q4")\ndept_avg <- rowMeans(scores)\nquarter_avg <- colMeans(scores)\nbest_dept <- names(which.max(dept_avg))\ndept_factor <- factor(rownames(scores))\nlevels(dept_factor)',
      'Department means are 86, 74.75, 92. Quarter means are approximately 84.6667, 89.3333, 79, 84. Sales has the highest mean. Factor levels are HR, IT, Sales.',
      [
        value('scores', 'matrix(c(88,92,79,85,75,81,69,74,91,95,89,93),nrow=3,byrow=TRUE)'),
        check(
          'exists("scores", inherits=FALSE) && identical(rownames(scores),c("IT","HR","Sales")) && identical(colnames(scores),c("Q1","Q2","Q3","Q4"))',
          'Add the department and quarter names.',
        ),
        value('dept_avg', 'c(86,74.75,92)'),
        value('quarter_avg', 'c(254/3,268/3,79,84)'),
        value('best_dept', '"Sales"'),
        check(
          'exists("dept_factor",inherits=FALSE) && is.factor(dept_factor) && identical(as.character(dept_factor),c("IT","HR","Sales")) && setequal(levels(dept_factor),c("HR","IT","Sales"))',
          'Create dept_factor from the department names and inspect its levels.',
        ),
      ],
      {
        source: 'Lab 3 · Exercise 5',
        hints: [
          'Use rowMeans() and colMeans(). Named row averages let you retrieve the winning name.',
          'best_dept <- names(which.max(dept_avg))\ndept_factor <- factor(rownames(scores))',
        ],
      },
    ),
  ],
  exam: [
    choice(
      'paper-modulo',
      'Division without running',
      'What does this expression return?',
      '(17 %% 5) + (17 %/% 5)',
      ['5', '7', '3.4'],
      0,
      '17 %% 5 is 2; 17 %/% 5 is 3. Their sum is 5.',
    ),
    choice(
      'paper-matrix',
      'Read a matrix',
      'What is m[2, 3]?',
      'm <- matrix(1:6, nrow = 2)',
      ['3', '5', '6'],
      2,
      'By default, R fills columns: column 1 is 1,2; column 2 is 3,4; column 3 is 5,6.',
    ),
    choice(
      'paper-list',
      'Extract from a list',
      'Which expression returns the numeric vector, rather than a one-element list?',
      'report <- list(sales = c(10, 20), label = "Q1")',
      ['report["sales"]', 'report[["sales"]]', 'names(report)'],
      1,
      'Double brackets extract a list element. Single brackets preserve a list containing the selected element.',
    ),
    choice(
      'paper-na',
      'Extend a vector',
      'What is x after these commands?',
      'x <- c(5, 10)\nx[4] <- 25',
      ['5, 10, 0, 25', '5, 10, NA, 25', '5, 10, 25'],
      1,
      'Assigning past the end extends the vector. The unassigned third position is NA.',
    ),
    choice(
      'paper-factor',
      'An unseen category',
      'What happens at the second line?',
      'f <- factor(c("A", "B"))\nf[1] <- "C"',
      [
        'C is added as a new level automatically.',
        'The first value becomes NA and R gives a warning.',
        'Both values become character strings.',
      ],
      1,
      'C is not an existing level. Add a level explicitly before assigning it, or recreate the factor.',
    ),
    choice(
      'paper-class',
      'Unclass a data frame',
      'What does class(unclass(df)) return?',
      'df <- data.frame(A = 1:3, B = 4:6)',
      ['NULL', '"data.frame"', '"list"'],
      2,
      'Removing the explicit data.frame class exposes the underlying list, whose implicit class is list.',
    ),
    written(
      'paper-simultaneous',
      'Two values change together',
      'Why is it wrong to update cityA before calculating the flow from cityA to cityB for the same year?',
      'Both annual flows must use the starting populations for that year. Calculate moveA and moveB first, then update both populations. Otherwise the second calculation uses an already changed value.',
    ),
    written(
      'paper-summary',
      'Write a table summary',
      'For scores with departments in rows and quarters in columns, write commands for average per department and average per quarter.',
      'dept_avg <- rowMeans(scores)\nquarter_avg <- colMeans(scores)\n\nRows represent departments and columns represent quarters. The meaning of each dimension determines the function.',
    ),
  ],
};
